# Generated by Django 3.2.5 on 2022-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('ProfessorId', models.AutoField(auto_created=True, db_column='آیدی', primary_key=True, serialize=False, unique=True, verbose_name='ایدی اساتید')),
                ('FirstName', models.CharField(db_column='نام', max_length=30, verbose_name='نام')),
                ('LastName', models.CharField(db_column='نام خانوادگی', max_length=30, verbose_name='نام خانوادگی')),
                ('Skill', models.CharField(db_column='مهارت ها', help_text='Skill seprate by , ', max_length=120, verbose_name='مهارت ها')),
                ('Age', models.IntegerField(db_column='سن')),
                ('ProfilePhoto', models.CharField(db_column='عکس پروفایل', default='No7ne', max_length=350, verbose_name='عکس پروفایل')),
                ('Status', models.BooleanField(db_column='وضعیت', default=True, verbose_name='وضعیت')),
            ],
        ),
    ]
