# Generated by Django 3.2.5 on 2022-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='Age',
            field=models.IntegerField(db_column='سن', verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='ProfilePhoto',
            field=models.CharField(db_column='عکس پروفایل', default='None', max_length=350, verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='Skill',
            field=models.CharField(db_column='مهارت ها', help_text='مهارت هایتان را با , جدا کنید', max_length=120, verbose_name='مهارت ها'),
        ),
    ]
