# Generated by Django 3.2.5 on 2022-01-18 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220118_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('TutorialId', models.AutoField(auto_created=True, db_column='آیدی', primary_key=True, serialize=False, unique=True, verbose_name='ایدی آموزش')),
                ('TutorialTitle', models.CharField(db_column='عنوان آموزش', max_length=30, verbose_name='عنوان آموزش')),
                ('Slug', models.SlugField(max_length=60)),
                ('Tags', models.CharField(db_column='تگ ها', help_text='تگ های مربوط به آموزش را بنویسید', max_length=120, verbose_name='تگ ها')),
                ('TutorialPeriod', models.IntegerField(db_column='مدت زمان', verbose_name='مدت زمان')),
                ('TutorialProfile', models.CharField(db_column='تصویر آموزش', default='None', max_length=350, verbose_name='تصویر آموزش')),
                ('Status', models.BooleanField(db_column='وضعیت', default=True, verbose_name='وضعیت')),
                ('Autor', models.CharField(db_column='استاد', max_length=30, verbose_name='استاد')),
            ],
        ),
    ]
