# Generated by Django 3.2.5 on 2022-01-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tutorial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('AutorId', models.AutoField(auto_created=True, db_column='آیدی', primary_key=True, serialize=False, unique=True, verbose_name='ایدی اساتید')),
                ('FirstName', models.CharField(db_column='نام', max_length=30, verbose_name='نام')),
                ('LastName', models.CharField(db_column='نام خانوادگی', max_length=30, verbose_name='نام خانوادگی')),
                ('Skill', models.CharField(db_column='مهارت ها', help_text='مهارت هایتان را با , جدا کنید', max_length=120, verbose_name='مهارت ها')),
                ('Age', models.IntegerField(db_column='سن', verbose_name='سن')),
                ('ProfilePhoto', models.CharField(db_column='عکس پروفایل', default='None', max_length=350, verbose_name='عکس پروفایل')),
                ('Status', models.BooleanField(db_column='وضعیت', default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'اساتید',
                'verbose_name_plural': 'استاد',
            },
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
