# Generated by Django 3.2.5 on 2022-01-19 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220119_1451'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name': 'دوره', 'verbose_name_plural': 'دوره ها'},
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Autor',
            field=models.ForeignKey(db_column='استاد', default=None, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.autor', verbose_name='استاد'),
        ),
    ]
