# Generated by Django 3.2.5 on 2022-01-19 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220119_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Autor',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='AutorId',
            new_name='AuthorId',
        ),
        migrations.RenameField(
            model_name='tutorial',
            old_name='Autor',
            new_name='Author',
        ),
    ]
