# Generated by Django 3.2.5 on 2022-01-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220119_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='Age',
            field=models.IntegerField(verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='author',
            name='AuthorId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ایدی اساتید'),
        ),
        migrations.AlterField(
            model_name='author',
            name='FirstName',
            field=models.CharField(max_length=30, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='author',
            name='ProfilePhoto',
            field=models.CharField(default='None', max_length=350, verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='author',
            name='Skill',
            field=models.CharField(help_text='مهارت هایتان را با , جدا کنید', max_length=120, verbose_name='مهارت ها'),
        ),
        migrations.AlterField(
            model_name='author',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Author',
            field=models.ForeignKey(default=None, max_length=30, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.author', verbose_name='استاد'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='Tags',
            field=models.CharField(help_text='تگ های مربوط به آموزش را بنویسید', max_length=120, verbose_name='تگ ها'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='TutorialId',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='ایدی آموزش'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='TutorialPeriod',
            field=models.IntegerField(verbose_name='مدت زمان'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='TutorialProfile',
            field=models.CharField(default='None', max_length=350, verbose_name='تصویر آموزش'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='TutorialTitle',
            field=models.CharField(max_length=30, verbose_name='عنوان آموزش'),
        ),
    ]
