# Generated by Django 3.2.5 on 2022-01-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220119_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='LastName',
            field=models.CharField(max_length=30, verbose_name='نام خانوادگی'),
        ),
    ]
