# Generated by Django 3.2.5 on 2022-01-19 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=50, verbose_name='نام')),
                ('LastName', models.CharField(max_length=50, verbose_name='نام خانوادگی')),
                ('Slug', models.SlugField(max_length=110)),
                ('Email', models.EmailField(max_length=120)),
                ('PhoneNumber', models.CharField(blank=True, max_length=15, null=True)),
                ('Sex', models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=10)),
                ('Education', models.CharField(max_length=60)),
                ('DataOfBirth', models.DateField(blank=True, null=True)),
                ('Bio', models.TextField(blank=True, null=True)),
                ('ProfilePhoto', models.CharField(blank=True, max_length=300, null=True)),
                ('Status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=85, verbose_name='عنوان')),
                ('Slug', models.SlugField(max_length=85)),
                ('Created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('Text', models.TextField()),
                ('ReadPeriad', models.IntegerField(null=True)),
                ('Tags', models.CharField(max_length=40)),
                ('Refrence', models.CharField(max_length=500)),
                ('Status', models.BooleanField(default=True)),
                ('Author', models.ManyToManyField(null=True, to='blog.Autor')),
            ],
        ),
    ]
