# Generated by Django 3.2.5 on 2022-01-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Author',
            field=models.ManyToManyField(to='blog.Autor', verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ReadPeriad',
            field=models.IntegerField(null=True, verbose_name='مدت زمان مطالعه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Refrence',
            field=models.CharField(max_length=500, null=True, verbose_name='منابع'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Tags',
            field=models.CharField(max_length=40, null=True, verbose_name='تگ های مربوط به مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='Text',
            field=models.TextField(verbose_name='متن مقاله'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='Bio',
            field=models.TextField(blank=True, null=True, verbose_name='بیوگرافی'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='DataOfBirth',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='Education',
            field=models.CharField(max_length=60, verbose_name='تحصیلات'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='Email',
            field=models.EmailField(max_length=120, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تلفن'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='ProfilePhoto',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='تصویر پروفایل'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='Sex',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن')], max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='Status',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
