# Generated by Django 3.2.5 on 2022-02-06 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Icon', models.CharField(max_length=10)),
                ('Title', models.CharField(max_length=25)),
                ('Slug', models.CharField(max_length=35)),
            ],
        ),
    ]
