# Generated by Django 3.2.5 on 2022-02-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_rename_admin_adminpanelitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanelitem',
            name='Icon',
            field=models.CharField(max_length=25),
        ),
    ]
