# Generated by Django 3.2.5 on 2022-02-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_alter_adminpanelitem_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpanelitem',
            name='Icon',
            field=models.CharField(default=None, max_length=25),
        ),
    ]
