# Generated by Django 3.2.5 on 2022-02-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_alter_adminpanelitem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminpanelitem',
            name='Status',
            field=models.BooleanField(default=True),
        ),
    ]
