# Generated by Django 3.2.5 on 2022-01-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=50)),
                ('AttributeStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryTitle', models.CharField(max_length=80)),
                ('Slug', models.SlugField(max_length=100)),
                ('CategoryStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductProperty',
            fields=[
                ('PropertyTitle', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('ProductPropertyStatus', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Image', models.CharField(max_length=450)),
                ('Title', models.CharField(max_length=250)),
                ('Brand', models.CharField(blank=True, max_length=120, null=True)),
                ('Slug', models.SlugField(max_length=450)),
                ('Price', models.CharField(max_length=35)),
                ('Discount', models.IntegerField(default=0)),
                ('Star', models.FloatField()),
                ('Status', models.BooleanField(default=True)),
                ('Attribute', models.ManyToManyField(to='commerce.Attribute')),
                ('Category', models.ManyToManyField(to='commerce.ProductCategory')),
            ],
        ),
        migrations.AddField(
            model_name='attribute',
            name='ProductProperty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commerce.productproperty'),
        ),
    ]
