# Generated by Django 3.2.5 on 2022-01-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='ProductPropertys',
            new_name='ProductProperty',
        ),
    ]
