# Generated by Django 3.2.5 on 2022-01-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_rename_productpropertys_attribute_productproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='ProductName',
            field=models.CharField(default=None, max_length=35),
            preserve_default=False,
        ),
    ]
