# Generated by Django 3.2.5 on 2022-01-23 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0002_alter_product_star'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
