# Generated by Django 3.2.5 on 2022-01-22 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_attribute_productname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attribute',
            old_name='ProductName',
            new_name='Product',
        ),
    ]
