# Generated by Django 3.2.5 on 2022-01-22 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_rename_productname_attribute_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='ProductProperty',
        ),
        migrations.AddField(
            model_name='attribute',
            name='ProductProperty',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commerce.productproperty'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='Attribute',
        ),
        migrations.AddField(
            model_name='product',
            name='Attribute',
            field=models.ManyToManyField(to='commerce.Attribute'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='Propperty',
        ),
        migrations.AddField(
            model_name='product',
            name='Propperty',
            field=models.ManyToManyField(to='commerce.ProductProperty'),
        ),
    ]
