# Generated by Django 3.2.5 on 2022-01-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_auto_20220128_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='SameProduct',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('MainImage', models.CharField(max_length=250)),
                ('Price', models.CharField(blank=True, max_length=35, null=True, verbose_name='Price ( $ )')),
                ('Discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Discount ( % )')),
                ('Status', models.BooleanField(default=True)),
                ('Attribute', models.ManyToManyField(to='commerce.Attribute')),
                ('Image', models.ManyToManyField(blank=True, null=True, to='commerce.ProductImage')),
            ],
        ),
    ]
