# Generated by Django 3.2.5 on 2022-01-28 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_sameproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Productd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.sameproduct'),
        ),
    ]
