# Generated by Django 3.2.5 on 2022-01-22 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_auto_20220122_1907'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Propperty',
        ),
    ]
