# Generated by Django 3.2.5 on 2022-01-22 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_remove_product_propperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='Product',
        ),
    ]
