# Generated by Django 3.2.5 on 2022-01-22 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0007_remove_attribute_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Attribute',
        ),
        migrations.AddField(
            model_name='product',
            name='Attribute',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commerce.attribute'),
            preserve_default=False,
        ),
    ]
