# Generated by Django 3.2.5 on 2022-01-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0008_auto_20220122_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Attribute',
        ),
        migrations.AddField(
            model_name='product',
            name='Attribute',
            field=models.ManyToManyField(to='commerce.Attribute'),
        ),
    ]
