# Generated by Django 3.2.5 on 2022-01-22 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_auto_20220122_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ProductImage',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='ProductStar',
            field=models.FloatField(default=None),
            preserve_default=False,
        ),
    ]
