# Generated by Django 4.0.2 on 2022-02-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Slug', models.SlugField()),
                ('Parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.category')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.CharField(max_length=85)),
                ('Title', models.CharField(max_length=50)),
                ('Level', models.CharField(default=None, max_length=20)),
                ('Slug', models.SlugField(max_length=100)),
                ('Category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.category')),
            ],
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('Id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePhoto', models.CharField(default=None, max_length=120)),
                ('FirstName', models.CharField(default=None, max_length=22)),
                ('LastName', models.CharField(default=None, max_length=22)),
                ('DateOfBirth', models.DateField(default=None)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Email', models.EmailField(max_length=35)),
                ('Role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.userrole')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Picture', models.CharField(max_length=85)),
                ('Title', models.CharField(max_length=50)),
                ('Slug', models.SlugField(max_length=100)),
                ('Description', models.TextField()),
                ('File', models.CharField(max_length=200)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Students',
            field=models.ManyToManyField(to='account.User'),
        ),
    ]
