# Generated by Django 3.2.5 on 2022-01-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MainImage',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
