# Generated by Django 3.2.5 on 2022-01-28 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_alter_product_productd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sameproduct',
            name='MainImage',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
