# Generated by Django 4.0.1 on 2022-02-03 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0009_alter_product_same'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Same',
            new_name='OtherProduct',
        ),
    ]
