# Generated by Django 4.0.1 on 2022-02-03 13:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0012_alter_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Ids',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='Id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
