# Generated by Django 4.0.1 on 2022-02-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0014_remove_product_ids_alter_productcategory_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ManyToManyField(to='commerce.ProductImage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='OtherProduct',
            field=models.ManyToManyField(to='commerce.SameProduct'),
        ),
    ]
