# Generated by Django 4.0.1 on 2022-02-03 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0015_alter_product_image_alter_product_otherproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ManyToManyField(blank=True, null=True, to='commerce.ProductImage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='OtherProduct',
            field=models.ManyToManyField(null=True, to='commerce.SameProduct'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='Parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.productcategory'),
        ),
        migrations.AlterField(
            model_name='sameproduct',
            name='Image',
            field=models.ManyToManyField(blank=True, null=True, to='commerce.ProductImage'),
        ),
    ]
