# Generated by Django 4.0.1 on 2022-02-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0016_alter_product_image_alter_product_otherproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='OtherProduct',
            field=models.ManyToManyField(blank=True, null=True, to='commerce.SameProduct'),
        ),
    ]
