# Generated by Django 4.0.1 on 2022-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0017_alter_product_otherproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='sameproduct',
            name='MainAttribute',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
