# Generated by Django 3.2.5 on 2022-03-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0018_sameproduct_mainattribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Earrings_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=20)),
                ('Slug', models.SlugField(max_length=65)),
            ],
        ),
    ]
