# Generated by Django 3.2.5 on 2022-03-30 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0019_earrings_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Color_name', models.CharField(max_length=20)),
                ('Color_code', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='OtherProduct',
        ),
        migrations.AddField(
            model_name='earrings_filter',
            name='SelectBox',
            field=models.BooleanField(default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='Same',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commerce.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='Image',
            field=models.ManyToManyField(default=None, null=True, to='commerce.ProductImage'),
        ),
        migrations.AlterField(
            model_name='product',
            name='MainImage',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.DeleteModel(
            name='SameProduct',
        ),
        migrations.AddField(
            model_name='product',
            name='Color',
            field=models.ManyToManyField(default=None, null=True, to='commerce.Color'),
        ),
    ]
