# Generated by Django 3.2.5 on 2022-03-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0020_auto_20220330_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Color',
            field=models.ManyToManyField(default=None, to='commerce.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Same',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='commerce.product'),
        ),
    ]
