# Generated by Django 3.2.5 on 2022-03-30 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0022_auto_20220330_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Same',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commerce.product'),
        ),
    ]
