# Generated by Django 3.2.5 on 2022-03-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Address',
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.EmailField(blank=True, default=None, max_length=45),
        ),
    ]
