# Generated by Django 3.2.5 on 2022-03-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220330_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='Email',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
    ]
